---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-bareos_dir
      bareos_dir_password: "secretpassword"
      bareos_dir_max_concurrent_jobs: 10
      bareos_dir_message: Daemon
      bareos_dir_clients:
        - name: client1
          address: 127.0.0.1
          password: "MySecretPassword"
      bareos_dir_storages:
        - name: File
          address: dir-1
          password: "MySecretPassword"
          device: FileStorage
          media_type: File
          tls_enable: yes
          tls_verify_peer: no
      bareos_dir_messages:
        - name: "Standard"
          description: "Send all messages to the Director."
          operatorcommand: "/usr/bin/bsmtp -h localhost -f \"(Bareos) <%r>\" -s \"Bareos: Intervention needed for %j\" %r"
          mailcommand: "/usr/bin/bsmtp -h localhost -f \"(Bareos) <%r>\" -s \"Bareos: %t %e of %c %l\" %r"
          operator: "root = mount"
          mail: "root = all, !skipped, !saved, !audit"
          console: "all, !skipped, !saved, !audit"
          append:
            file: "/var/log/bareos/bareos.log"
            messages:
              - all
              - "!skipped"
              - "!terminate"
              - "!audit"
          catalog: "all, !skipped, !saved, !audit"
      bareos_dir_profiles:
        - name: webui-admin
          jobacl:
            - "*all*"
          clientacl:
            - "*all*"
          storageacl:
            - "*all*"
          scheduleacl:
            - "*all*"
          poolacl:
            - "*all*"
          commandacl:
            - "!.bvfs_clear_cache"
            - "!.exit"
            - "!.sql"
            - "!configure"
            - "!create"
            - "!delete"
            - "!purge"
            - "!prune"
            - "!sqlquery"
            - "!umount"
            - "!unmount"
            - "*all*"
          filesetacl:
            - "*all*"
          catalogacl:
            - "*all*"
          whereacl:
            - "*all*"
          pluginoptionsacl:
            - "*all*"
