---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Check if port 9101 is listening
      ansible.builtin.wait_for:
        port: 9101

    - name: Test configuration
      ansible.builtin.command:
        cmd: bareos-dir --test-config
      become_user: bareos
