---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Check if port 9101 is listening
      ansible.builtin.wait_for:
        port: 9101
    # Add something with bconsole, to check status of dir.
